/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.LabAssistant;

import Backend.Enterprise.Enterprise;
import Backend.Organization.InventoryManagerOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import Backend.WorkQueue.CoordinatorTestWorkRequest;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ap
 */
public class AnalyseRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUsersJPanel
     */
     private CoordinatorTestWorkRequest request ;
    private Enterprise enterprise ;
    private UserAccount userAccount;
    public AnalyseRequestJPanel(CoordinatorTestWorkRequest request , Enterprise enterprise,UserAccount userAccount) {
        initComponents();
        this.request = request ; 
        this.enterprise = enterprise ;
        this.userAccount = userAccount;
        approveButton.setEnabled(false);
        rejectButton.setEnabled(false);
        ButtonGroup bloodTest = new ButtonGroup();
        bloodTest.add(BloodTesFailRadioButton);
        bloodTest.add(BloodTestPassRadioButton);
        
        
        ButtonGroup tissueTest = new ButtonGroup();
        tissueTest.add(tissuePassRadioButton);
        tissueTest.add(tissueFailRadioButton);
        
        ButtonGroup psychiatricTest = new ButtonGroup();
        psychiatricTest.add(psychiatricFailRadioButton);
        psychiatricTest.add(psychiatricPassRadioButton);
        
        ButtonGroup xrayTest = new ButtonGroup();
        xrayTest.add(tissuePassRadioButton);
        xrayTest.add(XrayFailRadioButton);
        
        ButtonGroup antiBodyTest = new ButtonGroup();
        antiBodyTest.add(heartNo);
        antiBodyTest.add(AntibodyPassRadioButton);
        
        ButtonGroup ArteriogramTest = new ButtonGroup();
        ArteriogramTest.add(asthamaNo);
        ArteriogramTest.add(ArteriogramPassRadioButton);
        
            
        ButtonGroup urineTest = new ButtonGroup();
        urineTest.add(asthamaNo1);
        urineTest.add(UrinePassRadioButton);
        
        populateDefault();
    }
    

    private void populateDefault() {
      userNameJTextField.setText(userAccount.getEmployee().getName());
      contactJTextField.setText(userAccount.getEmployee().getContactNumber()+"");
      dobJTextField1.setText(userAccount.getEmployee().getDateOfBirth().toString());
      genderNameJTextField1.setText(userAccount.getEmployee().getGender());      
      emergencyContactJTextField.setText(userAccount.getEmployee().getEmergencyContactNumber()+ "");
      approveButton.setEnabled(false);
      rejectButton.setEnabled(false);
    if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        pictureLabel.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
    }
  private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        BloodTesFailRadioButton = new javax.swing.JRadioButton();
        tissuePassRadioButton = new javax.swing.JRadioButton();
        tissueFailRadioButton = new javax.swing.JRadioButton();
        psychiatricPassRadioButton = new javax.swing.JRadioButton();
        psychiatricFailRadioButton = new javax.swing.JRadioButton();
        XrayPassRadioButton = new javax.swing.JRadioButton();
        XrayFailRadioButton = new javax.swing.JRadioButton();
        AntibodyPassRadioButton = new javax.swing.JRadioButton();
        heartNo = new javax.swing.JRadioButton();
        ArteriogramPassRadioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        asthamaNo = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BloodTestPassRadioButton = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        UrinePassRadioButton = new javax.swing.JRadioButton();
        asthamaNo1 = new javax.swing.JRadioButton();
        rejectButton = new javax.swing.JButton();
        approveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameSeparator2 = new javax.swing.JSeparator();
        userNameJTextField = new javax.swing.JTextField();
        nameSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nameSeparator = new javax.swing.JSeparator();
        contactJTextField = new javax.swing.JTextField();
        nameSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emergencyContactJTextField = new javax.swing.JTextField();
        nameSeparator8 = new javax.swing.JSeparator();
        pictureLabel = new javax.swing.JLabel();
        dobJTextField1 = new javax.swing.JTextField();
        genderNameJTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 539));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mandatory Tests");

        BloodTesFailRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        BloodTesFailRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        BloodTesFailRadioButton.setText("No");
        BloodTesFailRadioButton.setBorder(null);

        tissuePassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        tissuePassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tissuePassRadioButton.setText("Pass");
        tissuePassRadioButton.setBorder(null);

        tissueFailRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        tissueFailRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        tissueFailRadioButton.setText("No");
        tissueFailRadioButton.setBorder(null);

        psychiatricPassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        psychiatricPassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        psychiatricPassRadioButton.setText("Pass");
        psychiatricPassRadioButton.setBorder(null);

        psychiatricFailRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        psychiatricFailRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        psychiatricFailRadioButton.setText("No");
        psychiatricFailRadioButton.setBorder(null);

        XrayPassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        XrayPassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        XrayPassRadioButton.setText("Pass");
        XrayPassRadioButton.setBorder(null);

        XrayFailRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        XrayFailRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        XrayFailRadioButton.setText("No");
        XrayFailRadioButton.setBorder(null);

        AntibodyPassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        AntibodyPassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        AntibodyPassRadioButton.setText("Pass");
        AntibodyPassRadioButton.setBorder(null);

        heartNo.setBackground(new java.awt.Color(55, 96, 128));
        heartNo.setForeground(new java.awt.Color(255, 255, 255));
        heartNo.setText("No");
        heartNo.setBorder(null);

        ArteriogramPassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        ArteriogramPassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        ArteriogramPassRadioButton.setText("Pass");
        ArteriogramPassRadioButton.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Blood Test");

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Tissue ");

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Psychiatric");

        asthamaNo.setBackground(new java.awt.Color(55, 96, 128));
        asthamaNo.setForeground(new java.awt.Color(255, 255, 255));
        asthamaNo.setText("No");
        asthamaNo.setBorder(null);

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Xray ");

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Anti Body");

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Arteriogram");

        BloodTestPassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        BloodTestPassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        BloodTestPassRadioButton.setText("Pass");
        BloodTestPassRadioButton.setBorder(null);
        BloodTestPassRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodTestPassRadioButtonActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Urine");

        UrinePassRadioButton.setBackground(new java.awt.Color(55, 96, 128));
        UrinePassRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        UrinePassRadioButton.setText("Pass");
        UrinePassRadioButton.setBorder(null);

        asthamaNo1.setBackground(new java.awt.Color(55, 96, 128));
        asthamaNo1.setForeground(new java.awt.Color(255, 255, 255));
        asthamaNo1.setText("No");
        asthamaNo1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(UrinePassRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(asthamaNo1)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                            .addComponent(ArteriogramPassRadioButton)
                            .addGap(18, 18, 18)
                            .addComponent(asthamaNo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(AntibodyPassRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(heartNo))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(XrayPassRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(XrayFailRadioButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(BloodTestPassRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(BloodTesFailRadioButton))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(tissuePassRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(tissueFailRadioButton)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(psychiatricPassRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(psychiatricFailRadioButton))))))
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UrinePassRadioButton)
                    .addComponent(asthamaNo1))
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BloodTestPassRadioButton)
                        .addComponent(BloodTesFailRadioButton))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tissuePassRadioButton)
                        .addComponent(tissueFailRadioButton))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(psychiatricPassRadioButton)
                        .addComponent(psychiatricFailRadioButton))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(XrayPassRadioButton)
                        .addComponent(XrayFailRadioButton))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AntibodyPassRadioButton)
                        .addComponent(heartNo))
                    .addGap(26, 26, 26)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ArteriogramPassRadioButton)
                        .addComponent(asthamaNo))
                    .addContainerGap(141, Short.MAX_VALUE)))
        );

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");

        nameSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        userNameJTextField.setBorder(null);
        userNameJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        userNameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameJTextFieldFocusGained(evt);
            }
        });
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Birth");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name");

        nameSeparator.setForeground(new java.awt.Color(255, 255, 255));

        contactJTextField.setBorder(null);
        contactJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        contactJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactJTextFieldFocusGained(evt);
            }
        });
        contactJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Emergency Contact");

        emergencyContactJTextField.setBorder(null);
        emergencyContactJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        emergencyContactJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emergencyContactJTextFieldFocusGained(evt);
            }
        });
        emergencyContactJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyContactJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        pictureLabel.setBackground(new java.awt.Color(255, 255, 255));
        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dobJTextField1.setBorder(null);

        genderNameJTextField1.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emergencyContactJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderNameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dobJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genderNameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emergencyContactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Analyse Requests");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        submitButton.setText("Submit ");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        TextField.setBackground(new java.awt.Color(0, 0, 0));
        TextField.setColumns(20);
        TextField.setForeground(new java.awt.Color(51, 153, 0));
        TextField.setRows(5);
        TextField.setAutoscrolls(false);
        jScrollPane1.setViewportView(TextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(submitButton)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(approveButton)
                            .addComponent(rejectButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        approveButton.setEnabled(false);
        submitButton.setEnabled(true);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof InventoryManagerOrganization) {
                org = organization;
                break;
            }
        }
        
        if (org != null) {
            request.setLabStatus("Completed");
            org.getWorkQueue().getWorkRequestList().add(request);
            request.setActionDate(new Date());
            JOptionPane.showMessageDialog(null, "Request Approved", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            if (request.getUser().getType() == 'd') {
                request.setOverallStatus("Request Approved by Lab Assistant , Waiting for potential Receiver");
                request.setInventoryStatus("in inventory");
            }
            else {
                 request.setOverallStatus("Request Approved by Lab Assistant , Waiting for potential Donor");
                 request.setInventoryStatus("in inventory");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Organization not present", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
    }//GEN-LAST:event_approveButtonActionPerformed

    private void userNameJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameJTextFieldFocusGained
        // TODO add your handling code here:
        userNameJTextField.setText("");
    }//GEN-LAST:event_userNameJTextFieldFocusGained

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void contactJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_contactJTextFieldFocusGained

    private void contactJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactJTextFieldActionPerformed

    private void emergencyContactJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergencyContactJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactJTextFieldFocusGained

    private void emergencyContactJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyContactJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactJTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:

         javax.swing.Timer timer3 = new javax.swing.Timer(0, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nStarting a new Process............................";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                }
            });
            timer3.start();  
        javax.swing.Timer timer = new javax.swing.Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nProcessing the Tests ...............";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                }
            });
            timer.start();  
            
             javax.swing.Timer timer1 = new javax.swing.Timer(4000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nValidating the Tests .............";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                }
            });
            timer1.start();    
        if (BloodTestPassRadioButton.isSelected() && tissuePassRadioButton.isSelected() && psychiatricPassRadioButton.isSelected()
            && AntibodyPassRadioButton.isSelected() && ArteriogramPassRadioButton.isSelected()
            && UrinePassRadioButton.isSelected()&&XrayPassRadioButton.isSelected()) { 
          javax.swing.Timer timer2 = new javax.swing.Timer(6000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nYou can approve the request!";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                        ((javax.swing.Timer)e.getSource()).stop();
                        approveButton.setEnabled(true);
                }
            });
            timer2.start();    
     
        
        }
        else {
        
              javax.swing.Timer timer2 = new javax.swing.Timer(6000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nReject the Request!";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                    ((javax.swing.Timer)e.getSource()).stop();
                    rejectButton.setEnabled(true);
                }
            });
            timer2.start();
            
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
         rejectButton.setEnabled(false);
         submitButton.setEnabled(true);
         request.setLabStatus("Rejected");
         request.setOverallStatus("Requestis Rejected by Lab Assistant");
         request.setActionDate(new Date());
         JOptionPane.showMessageDialog(null, "Request Rejected" ,"Info" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void BloodTestPassRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodTestPassRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodTestPassRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AntibodyPassRadioButton;
    private javax.swing.JRadioButton ArteriogramPassRadioButton;
    private javax.swing.JRadioButton BloodTesFailRadioButton;
    private javax.swing.JRadioButton BloodTestPassRadioButton;
    private javax.swing.JTextArea TextField;
    private javax.swing.JRadioButton UrinePassRadioButton;
    private javax.swing.JRadioButton XrayFailRadioButton;
    private javax.swing.JRadioButton XrayPassRadioButton;
    private javax.swing.JButton approveButton;
    private javax.swing.JRadioButton asthamaNo;
    private javax.swing.JRadioButton asthamaNo1;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JTextField dobJTextField1;
    private javax.swing.JTextField emergencyContactJTextField;
    private javax.swing.JTextField genderNameJTextField1;
    private javax.swing.JRadioButton heartNo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator8;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JRadioButton psychiatricFailRadioButton;
    private javax.swing.JRadioButton psychiatricPassRadioButton;
    private javax.swing.JButton rejectButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton tissueFailRadioButton;
    private javax.swing.JRadioButton tissuePassRadioButton;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
