/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.Donor;

import UI.Receiver.ManageRequestReceiverJPanel;
import UI.Coordinator.*;
import UI.Admin.*;
import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.User.User;
import MainPages.LoginPage;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author ap
 */
public class DonorDashBoardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDashBoardJPanel
     */

   private DB4OUtil dB4OUtil;
    private EcoSystem system;
    private User user;
    public DonorDashBoardJPanel(DB4OUtil dB4OUtil,EcoSystem system,User user) {
        initComponents();
       this.dB4OUtil = dB4OUtil;
        this.system = system;
        this.user =user;
         setColor(manageProfileDonor);
        resetColor(new JPanel[]{manageRequest});
        ManageDonorDetailsJPanel jpanel = new ManageDonorDetailsJPanel(user,system);
        userProcessContainer.add("ManageDonorDetailsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        manageAdmin = new javax.swing.JPanel();
        manageProfileDonor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        manageRequest = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(974, 682));

        jSplitPane4.setBackground(new java.awt.Color(102, 102, 102));
        jSplitPane4.setDividerSize(0);

        manageAdmin.setBackground(new java.awt.Color(255, 255, 255));
        manageAdmin.setPreferredSize(new java.awt.Dimension(200, 798));

        manageProfileDonor.setBackground(new java.awt.Color(0, 0, 0));
        manageProfileDonor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageProfileDonorMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Profile");

        javax.swing.GroupLayout manageProfileDonorLayout = new javax.swing.GroupLayout(manageProfileDonor);
        manageProfileDonor.setLayout(manageProfileDonorLayout);
        manageProfileDonorLayout.setHorizontalGroup(
            manageProfileDonorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
        );
        manageProfileDonorLayout.setVerticalGroup(
            manageProfileDonorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageProfileDonorLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        manageRequest.setBackground(new java.awt.Color(0, 0, 0));
        manageRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageRequestMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Request");

        javax.swing.GroupLayout manageRequestLayout = new javax.swing.GroupLayout(manageRequest);
        manageRequest.setLayout(manageRequestLayout);
        manageRequestLayout.setHorizontalGroup(
            manageRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRequestLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageRequestLayout.setVerticalGroup(
            manageRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout manageAdminLayout = new javax.swing.GroupLayout(manageAdmin);
        manageAdmin.setLayout(manageAdminLayout);
        manageAdminLayout.setHorizontalGroup(
            manageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageProfileDonor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manageRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        manageAdminLayout.setVerticalGroup(
            manageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAdminLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(manageProfileDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manageRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(535, 535, 535))
        );

        jSplitPane4.setLeftComponent(manageAdmin);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageRequestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRequestMousePressed
        // TODO add your handling code here:
        setColor(manageRequest);
        resetColor(new JPanel[]{manageProfileDonor});
        DonorRequestJPanel donorRequest = new DonorRequestJPanel(system,user);
        userProcessContainer.add("ManageDonorDetailsJPanel",donorRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRequestMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.dispose();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_exitMousePressed

    private void manageProfileDonorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfileDonorMousePressed
        // TODO add your handling code here:
        setColor(manageProfileDonor);
        resetColor(new JPanel[]{manageRequest});
        ManageDonorDetailsJPanel jpanel = new ManageDonorDetailsJPanel(user,system);
        userProcessContainer.add("ManageDonorDetailsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageProfileDonorMousePressed

 private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(255,102,102));
    }
    
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JPanel manageAdmin;
    private javax.swing.JPanel manageProfileDonor;
    private javax.swing.JPanel manageRequest;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
