/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.Donor;

import Backend.EcoSystem;
import Backend.User.User;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
 
/**
 *
 * @author ap
 */
public class ManageDonorDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDetailsJPanel
     */
    private EcoSystem system;
    private User user;
    private byte[] tempdP;

    public ManageDonorDetailsJPanel(User user, EcoSystem system) {
        initComponents();
        this.system = system;
        this.user = user;
        ButtonGroup buttongroup = new ButtonGroup();
        buttongroup.add(heartCheckBox);
        buttongroup.add(liverCheckBox);
        buttongroup.add(kidneyCheckBox);
        buttongroup.add(eyesCheckBox);
        buttongroup.add(lungsCheckBox);
        populateDefault();
    }

    private void populateDefault() {
        saveButton.setEnabled(false);
        uploadButton.setEnabled(false);
        genderComboBox.removeAllItems();
        genderComboBox.addItem("Male");
        genderComboBox.addItem("Female");
        userNameJTextField.setText(user.getName());
        addressJTextField.setText(user.getAddress());
        cityJTextField.setText(user.getCity());
        contactJTextField.setText(user.getContactNumber());
        jXDatePicker1.setDate(user.getDateOfBirth());
        genderComboBox.setSelectedItem(user.getGender());
        //emergencyContactJTextField.setText(user.getEmergencyContactNumber()+ "");
            emergencyContactJTextField.setText(user.getEmergencyContactNumber());
        relationJTextField.setText(user.getRelation());
        stateJTextField.setText(user.getState());
        //zipJTextField.setText(user.getZip()+ "");
            zipJTextField.setText(user.getZip());
        heartCheckBox.setSelected(user.isHeart());
        kidneyCheckBox.setSelected(user.isKidney());
        liverCheckBox.setSelected(user.isLiver());
        lungsCheckBox.setSelected(user.isLungs());
        eyesCheckBox.setSelected(user.isEyes());
        addressJTextField.setEditable(false);
        cityJTextField.setEditable(false);
        contactJTextField.setEditable(false);
        jXDatePicker1.setEditable(false);
        genderComboBox.setEnabled(false);
        emergencyContactJTextField.setEditable(false);
        stateJTextField.setEditable(false);
        relationJTextField.setEditable(false);
        zipJTextField.setEditable(false); 
        heartCheckBox.setEnabled(false);
        kidneyCheckBox.setEnabled(false);
        liverCheckBox.setEnabled(false);
        lungsCheckBox.setEnabled(false);
        eyesCheckBox.setEnabled(false);  
       
        if(user.getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = user.getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        pictureLabel.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
    }
private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nameSeparator3 = new javax.swing.JSeparator();
        userNameJTextField = new javax.swing.JTextField();
        cityJTextField = new javax.swing.JTextField();
        nameSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameSeparator1 = new javax.swing.JSeparator();
        contactJTextField = new javax.swing.JTextField();
        nameSeparator = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        stateJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nameSeparator7 = new javax.swing.JSeparator();
        nameSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        zipJTextField = new javax.swing.JTextField();
        pictureLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        nameSeparator5 = new javax.swing.JSeparator();
        nameSeparator6 = new javax.swing.JSeparator();
        nameSeparator9 = new javax.swing.JSeparator();
        relationJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nameSeparator8 = new javax.swing.JSeparator();
        emergencyContactJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nameSeparator10 = new javax.swing.JSeparator();
        relationNameJTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        kidneyCheckBox = new javax.swing.JCheckBox();
        eyesCheckBox = new javax.swing.JCheckBox();
        liverCheckBox = new javax.swing.JCheckBox();
        lungsCheckBox = new javax.swing.JCheckBox();
        heartCheckBox = new javax.swing.JCheckBox();
        nameSeparator11 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        uploadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 539));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(947, 700));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("Address");

        nameSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        userNameJTextField.setEditable(false);
        userNameJTextField.setBorder(null);
        userNameJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        userNameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameJTextFieldFocusGained(evt);
            }
        });
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        cityJTextField.setBorder(null);
        cityJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        cityJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityJTextFieldFocusGained(evt);
            }
        });
        cityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("City");

        addressJTextField.setBorder(null);
        addressJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        addressJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressJTextFieldFocusGained(evt);
            }
        });
        addressJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("Contact");

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        contactJTextField.setBorder(null);
        contactJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        contactJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactJTextFieldFocusGained(evt);
            }
        });
        contactJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel2.setText("Name");

        stateJTextField.setBorder(null);
        stateJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        stateJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateJTextFieldFocusGained(evt);
            }
        });
        stateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setText("State");

        nameSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setText("Zip Code");

        zipJTextField.setBorder(null);
        zipJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        zipJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipJTextFieldFocusGained(evt);
            }
        });
        zipJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipJTextFieldActionPerformed(evt);
            }
        });

        pictureLabel.setBackground(new java.awt.Color(255, 255, 255));
        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setText("Gender");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Date of Birth");

        jXDatePicker1.setBackground(new java.awt.Color(255, 255, 255));

        nameSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        nameSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        relationJTextField.setBorder(null);
        relationJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        relationJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                relationJTextFieldFocusGained(evt);
            }
        });
        relationJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationJTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel12.setText("Relation");

        nameSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        emergencyContactJTextField.setBorder(null);
        emergencyContactJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        emergencyContactJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emergencyContactJTextFieldFocusGained(evt);
            }
        });
        emergencyContactJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyContactJTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel11.setText("Emergency Contact");

        nameSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        relationNameJTextField.setBorder(null);
        relationNameJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        relationNameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                relationNameJTextFieldFocusGained(evt);
            }
        });
        relationNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationNameJTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel14.setText("Name of Contact");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("What organ you wanted to donate?");

        kidneyCheckBox.setBackground(new java.awt.Color(93, 113, 128));
        kidneyCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        kidneyCheckBox.setText("Kidneys");
        kidneyCheckBox.setBorder(null);
        kidneyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kidneyCheckBoxActionPerformed(evt);
            }
        });

        eyesCheckBox.setBackground(new java.awt.Color(93, 113, 128));
        eyesCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        eyesCheckBox.setText("Eyes");
        eyesCheckBox.setBorder(null);

        liverCheckBox.setBackground(new java.awt.Color(93, 113, 128));
        liverCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        liverCheckBox.setText("Liver");
        liverCheckBox.setBorder(null);

        lungsCheckBox.setBackground(new java.awt.Color(93, 113, 128));
        lungsCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        lungsCheckBox.setText("Lungs");
        lungsCheckBox.setBorder(null);

        heartCheckBox.setBackground(new java.awt.Color(93, 113, 128));
        heartCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        heartCheckBox.setText("Heart");
        heartCheckBox.setBorder(null);

        nameSeparator11.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(kidneyCheckBox)
                    .addComponent(eyesCheckBox)
                    .addComponent(liverCheckBox)
                    .addComponent(lungsCheckBox)
                    .addComponent(heartCheckBox)
                    .addComponent(nameSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(kidneyCheckBox)
                .addGap(5, 5, 5)
                .addComponent(eyesCheckBox)
                .addGap(5, 5, 5)
                .addComponent(liverCheckBox)
                .addGap(5, 5, 5)
                .addComponent(lungsCheckBox)
                .addGap(5, 5, 5)
                .addComponent(heartCheckBox)
                .addGap(11, 11, 11)
                .addComponent(nameSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Donor Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        uploadButton.setBackground(new java.awt.Color(171, 204, 67));
        uploadButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(171, 204, 67));
        saveButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(171, 204, 67));
        updateButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(zipJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emergencyContactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(relationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(relationNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(uploadButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(uploadButton)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(3, 3, 3)
                                .addComponent(contactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nameSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel11)
                                .addGap(6, 6, 6)
                                .addComponent(emergencyContactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(relationJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(saveButton))
                                .addGap(1, 1, 1)
                                .addComponent(relationNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(nameSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(updateButton)))
                                .addGap(48, 48, 48))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(6, 6, 6)
                                        .addComponent(stateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(nameSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(6, 6, 6)
                                        .addComponent(zipJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(nameSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(6, 6, 6)
                                        .addComponent(cityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(122, 122, 122)))))
                        .addGap(70, 70, 70))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kidneyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kidneyCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kidneyCheckBoxActionPerformed

    private void userNameJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameJTextFieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_userNameJTextFieldFocusGained

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void contactJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_contactJTextFieldFocusGained

    private void contactJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactJTextFieldActionPerformed

    private void addressJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTextFieldFocusGained

    private void addressJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTextFieldActionPerformed

    private void cityJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextFieldFocusGained

    private void cityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextFieldActionPerformed

    private void stateJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJTextFieldFocusGained

    private void stateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJTextFieldActionPerformed

    private void zipJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_zipJTextFieldFocusGained

    private void zipJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipJTextFieldActionPerformed

    private void emergencyContactJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergencyContactJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactJTextFieldFocusGained

    private void emergencyContactJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyContactJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyContactJTextFieldActionPerformed

    private void relationJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_relationJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_relationJTextFieldFocusGained

    private void relationJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationJTextFieldActionPerformed

    private void relationNameJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_relationNameJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_relationNameJTextFieldFocusGained

    private void relationNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationNameJTextFieldActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.dir")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              tempdP = new byte[(int) selectedFile.length()]; 
                FileInputStream fis;
             try {
                 fis = new FileInputStream(selectedFile);
                 fis.read(tempdP);
                 fis.close();
             } catch (IOException ex) {
                 Logger.getLogger(ManageDonorDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }             
              pictureLabel.setIcon(ResizeImage(selectedFile.getAbsolutePath()));
              pictureLabel.setIcon(setPicture(selectedFile.getAbsolutePath(),pictureLabel));
          }

          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private ImageIcon setPicture(String carImageLocation, JLabel carImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(carImageLocation);
        Image picCar = imageCar.getImage();
        Image resizedImage = picCar.getScaledInstance(carImage.getWidth(), carImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}
   

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String pattern = ".*\\D.*";
        Pattern patternForZip = Pattern.compile(pattern);
        String zipCode1 = zipJTextField.getText();
        String emergencyContact = emergencyContactJTextField.getText();
        String contact = contactJTextField.getText();
        Matcher matcherForZip = patternForZip.matcher(zipCode1);
         Matcher matcherForContact = patternForZip.matcher(contact);
           Matcher matcherForEContact = patternForZip.matcher(emergencyContact);
        if (matcherForZip.matches() == true || matcherForContact.matches() == true|| matcherForEContact.matches() == true) {
            JOptionPane.showMessageDialog(null, "Contact Number and Zip code should be numeric", "Error", 0);
			return;
        }
         
        if (addressJTextField.getText().isEmpty()           || cityJTextField.getText().isEmpty()     ||
            contactJTextField.getText().isEmpty()           || relationJTextField.getText().isEmpty() ||
            emergencyContactJTextField.getText().isEmpty()  || stateJTextField.getText().isEmpty()    ||
            zipJTextField.getText().isEmpty()               || userNameJTextField.getText().isEmpty() ||
            relationNameJTextField.getText().isEmpty() )
        { 
    
         JOptionPane.showMessageDialog(null, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
         return ;
        }
        
          Date currentDate = new Date();
          
          if (currentDate.equals(jXDatePicker1.getDate()) || jXDatePicker1.getDate().after(currentDate)) {
          
             JOptionPane.showMessageDialog(null, "Date should be past date", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
          
          if (contactJTextField.getText().length() != 10 || emergencyContactJTextField.getText().length() != 10) {
             JOptionPane.showMessageDialog(null, "Contact information should be 10 number", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (zipJTextField.getText().length() != 5) {
             JOptionPane.showMessageDialog(null, "Zip code should be 5 digit", "Error", JOptionPane.ERROR_MESSAGE);
             return;   
          }
          
          if (kidneyCheckBox.isSelected() || heartCheckBox.isSelected() || eyesCheckBox.isSelected()
              || liverCheckBox.isSelected() || lungsCheckBox.isSelected()) {
          user.setAddress(addressJTextField.getText());
        user.setCity(cityJTextField.getText());
        user.setContactNumber(contactJTextField.getText());
        user.setDateOfBirth(jXDatePicker1.getDate());
        user.setGender((String) genderComboBox.getSelectedItem());
        user.setEmergencyContactNumber(emergencyContactJTextField.getText());
        user.setRelation(relationNameJTextField.getText());
        user.setState(stateJTextField.getText());
        user.setZip(zipJTextField.getText());
        user.setHeart(heartCheckBox.isSelected());
        user.setKidney(kidneyCheckBox.isSelected());
        user.setLiver(liverCheckBox.isSelected());
        user.setLungs(lungsCheckBox.isSelected());
        user.setEyes(eyesCheckBox.isSelected());
        user.setPictureLabel(pictureLabel);
        user.setdP(tempdP);
        JOptionPane.showMessageDialog(null, "Profile Updated Sucessfully");
        user.setCompleteProfile(true);
        addressJTextField.setEditable(false);
        cityJTextField.setEditable(false);
        contactJTextField.setEditable(false);
        jXDatePicker1.setEnabled(false);
        genderComboBox.setEnabled(false);
        emergencyContactJTextField.setEditable(false);
        stateJTextField.setEditable(false);
        relationNameJTextField.setEditable(false);
        zipJTextField.setEditable(false); 
        heartCheckBox.setEnabled(false);
        kidneyCheckBox.setEnabled(false);
        liverCheckBox.setEnabled(false);
        lungsCheckBox.setEnabled(false);
        eyesCheckBox.setEnabled(false);     
        updateButton.setEnabled(true);
        saveButton.setEnabled(false);
        uploadButton.setEnabled(false);
            
          }
          else{
          JOptionPane.showMessageDialog(null, "Please select organ to donate", "Error", JOptionPane.ERROR_MESSAGE);
             return;
          }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateButton.setEnabled(false);
        saveButton.setEnabled(true);
        uploadButton.setEnabled(true);
        addressJTextField.setEditable(true);
        cityJTextField.setEditable(true);
        contactJTextField.setEditable(true);
        jXDatePicker1.setEditable(true);
        genderComboBox.setEnabled(true);
        emergencyContactJTextField.setEditable(true);
        stateJTextField.setEditable(true);
        relationJTextField.setEditable(true);
        zipJTextField.setEditable(true); 
        heartCheckBox.setEnabled(true);
        kidneyCheckBox.setEnabled(true);
        liverCheckBox.setEnabled(true);
        lungsCheckBox.setEnabled(true);
        eyesCheckBox.setEnabled(true); 
    }//GEN-LAST:event_updateButtonActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JTextField cityJTextField;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JTextField emergencyContactJTextField;
    private javax.swing.JCheckBox eyesCheckBox;
    private javax.swing.JComboBox genderComboBox;
    private javax.swing.JCheckBox heartCheckBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JCheckBox kidneyCheckBox;
    private javax.swing.JCheckBox liverCheckBox;
    private javax.swing.JCheckBox lungsCheckBox;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator10;
    private javax.swing.JSeparator nameSeparator11;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JSeparator nameSeparator5;
    private javax.swing.JSeparator nameSeparator6;
    private javax.swing.JSeparator nameSeparator7;
    private javax.swing.JSeparator nameSeparator8;
    private javax.swing.JSeparator nameSeparator9;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JTextField relationJTextField;
    private javax.swing.JTextField relationNameJTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stateJTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton uploadButton;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JTextField zipJTextField;
    // End of variables declaration//GEN-END:variables

}
