/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.Doctor;

import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Organization.DoctorOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author ms
 */
public class DoctorDashBoardJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserDashBoardJPanel
     */

    private EcoSystem system;
    private Enterprise enterprise ;
    private DB4OUtil dB4OUtil;
    private UserAccount userAccount;
    private DoctorOrganization docOrganization;
    public DoctorDashBoardJPanel(UserAccount account, Organization organization, EcoSystem system,DB4OUtil dB4OUtil,Enterprise enterprise) {
        initComponents();
        this.dB4OUtil = dB4OUtil;
        this.system = system;
         this.enterprise = enterprise ;
        this.dB4OUtil = dB4OUtil;
        this.system = system;
        this.userAccount =account;
        this.docOrganization = (DoctorOrganization)organization;
          setColor(profileDoctorBtn);
        resetColor(new JPanel[]{manageRequestDoctor});
        ManageDoctorDetailsJPanel jpanel = new ManageDoctorDetailsJPanel(userAccount,system,docOrganization,enterprise);
        userProcessContainer.add("ManageDoctorDetailsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane4 = new javax.swing.JSplitPane();
        manageAdmin = new javax.swing.JPanel();
        manageRequestDoctor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        profileDoctorBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(974, 682));

        jSplitPane4.setBackground(new java.awt.Color(55, 96, 128));
        jSplitPane4.setDividerSize(0);

        manageAdmin.setBackground(new java.awt.Color(255, 255, 255));

        manageRequestDoctor.setBackground(new java.awt.Color(0, 0, 0));
        manageRequestDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageRequestDoctorMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Requests");

        javax.swing.GroupLayout manageRequestDoctorLayout = new javax.swing.GroupLayout(manageRequestDoctor);
        manageRequestDoctor.setLayout(manageRequestDoctorLayout);
        manageRequestDoctorLayout.setHorizontalGroup(
            manageRequestDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRequestDoctorLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageRequestDoctorLayout.setVerticalGroup(
            manageRequestDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRequestDoctorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        profileDoctorBtn.setBackground(new java.awt.Color(0, 0, 0));
        profileDoctorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profileDoctorBtnMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Profile");

        javax.swing.GroupLayout profileDoctorBtnLayout = new javax.swing.GroupLayout(profileDoctorBtn);
        profileDoctorBtn.setLayout(profileDoctorBtnLayout);
        profileDoctorBtnLayout.setHorizontalGroup(
            profileDoctorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDoctorBtnLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileDoctorBtnLayout.setVerticalGroup(
            profileDoctorBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDoctorBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout manageAdminLayout = new javax.swing.GroupLayout(manageAdmin);
        manageAdmin.setLayout(manageAdminLayout);
        manageAdminLayout.setHorizontalGroup(
            manageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageRequestDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(profileDoctorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageAdminLayout.setVerticalGroup(
            manageAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAdminLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(profileDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(manageRequestDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(manageAdmin);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane4.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageRequestDoctorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRequestDoctorMousePressed
        // TODO add your handling code here:
        setColor(manageRequestDoctor);
        resetColor(new JPanel[]{profileDoctorBtn});
        DoctorManageRequestsJPanel jpanel = new DoctorManageRequestsJPanel(userProcessContainer,userAccount,docOrganization , system,  enterprise);
        userProcessContainer.add("ManageRequestsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRequestDoctorMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.dispose();
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_exitMousePressed

    private void profileDoctorBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileDoctorBtnMousePressed
        // TODO add your handling code here:
        setColor(profileDoctorBtn);
        resetColor(new JPanel[]{manageRequestDoctor});
        ManageDoctorDetailsJPanel jpanel = new ManageDoctorDetailsJPanel(userAccount,system,docOrganization,enterprise);
        userProcessContainer.add("ManageDoctorDetailsJPanel",jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_profileDoctorBtnMousePressed

 private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(255,102,102));
    }
    
    private void resetColor(JPanel [] pane)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } 
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JPanel manageAdmin;
    private javax.swing.JPanel manageRequestDoctor;
    private javax.swing.JPanel profileDoctorBtn;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
