/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin.Coordinator;

import Backend.Enterprise.Enterprise;
import Backend.Organization.LabOrganization;
import Backend.Organization.Organization;
import Backend.UserAccount.UserAccount;
import Backend.WorkQueue.CoordinatorTestWorkRequest;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ms
 */
public class CoordinatorMedicalCheckDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUsersJPanel
     */
    private CoordinatorTestWorkRequest request ;
    private Enterprise enterprise ;
    private UserAccount userAccount;
    public CoordinatorMedicalCheckDetailsJPanel(CoordinatorTestWorkRequest request , Enterprise enterprise,UserAccount userAccount) {
      initComponents();
        this.request = request ; 
        this.enterprise = enterprise ;
        this.userAccount= userAccount;
        approveButton.setEnabled(false);
        rejectButton.setEnabled(false);
         ButtonGroup sugar = new ButtonGroup();
         sugar.add(sugarYes);
         sugar.add(sugarNo);
         
         ButtonGroup aids = new ButtonGroup();
         aids.add(aidsYes);
         aids.add(aidsNo);
         
         ButtonGroup tatto = new ButtonGroup();
         tatto.add(tattooYes);
         tatto.add(tattooNo);
         
         ButtonGroup diabetes = new ButtonGroup();
         diabetes.add(diabetesYes);
         diabetes.add(diabetesNo);
         
         ButtonGroup heart = new ButtonGroup();
         heart.add(heartYes);
         heart.add(heartNo);
         
         ButtonGroup asthama = new ButtonGroup();
         asthama.add(asthamaYes);
         asthama.add(asthamaNo);     
        populateDefault();
        
    }
    

   private void populateDefault() {
      userNameJTextField.setText(userAccount.getEmployee().getName());
      contactNumberJTextField.setText(userAccount.getEmployee().getContactNumber()+"");
      dobJTextField.setText(userAccount.getEmployee().getDateOfBirth().toString());
      genderNameJTextField.setText(userAccount.getEmployee().getGender());      
      emergencyJTextField.setText(userAccount.getEmployee().getEmergencyContactNumber()+ "");
         if(userAccount.getEmployee().getdP() !=null){
        //Working line
         byte[] JLabelpictureLabel = userAccount.getEmployee().getdP();
        ImageIcon i = setPicturebyte(JLabelpictureLabel);
        pictureLabel.setIcon(i);
        }
        else{
            System.err.println("No Image");
        }
    }
  private ImageIcon setPicturebyte(byte[] byteArrayImage){

        ImageIcon imageCar;
        imageCar = new ImageIcon(byteArrayImage);
        Image picCar = imageCar.getImage();
        JLabel pictureLabel1 = new JLabel();
        pictureLabel1.setSize(107, 133);
        Image resizedImage = picCar.getScaledInstance(pictureLabel1.getWidth(), pictureLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon selectedCarPicture = new ImageIcon(resizedImage);
        return selectedCarPicture;  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sugarYes = new javax.swing.JRadioButton();
        sugarNo = new javax.swing.JRadioButton();
        aidsYes = new javax.swing.JRadioButton();
        aidsNo = new javax.swing.JRadioButton();
        tattooYes = new javax.swing.JRadioButton();
        tattooNo = new javax.swing.JRadioButton();
        diabetesYes = new javax.swing.JRadioButton();
        diabetesNo = new javax.swing.JRadioButton();
        heartYes = new javax.swing.JRadioButton();
        heartNo = new javax.swing.JRadioButton();
        asthamaYes = new javax.swing.JRadioButton();
        asthamaNo = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rejectButton = new javax.swing.JButton();
        approveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameSeparator2 = new javax.swing.JSeparator();
        userNameJTextField = new javax.swing.JTextField();
        nameSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nameSeparator = new javax.swing.JSeparator();
        contactNumberJTextField = new javax.swing.JTextField();
        nameSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emergencyJTextField = new javax.swing.JTextField();
        nameSeparator8 = new javax.swing.JSeparator();
        dobJTextField = new javax.swing.JTextField();
        genderNameJTextField = new javax.swing.JTextField();
        pictureLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(890, 539));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mandatory Tests");

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Diebeties");

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tattoo");

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Heart");

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Asthama");

        sugarYes.setBackground(new java.awt.Color(55, 96, 128));
        sugarYes.setForeground(new java.awt.Color(255, 255, 255));
        sugarYes.setText("Yes");
        sugarYes.setBorder(null);

        sugarNo.setBackground(new java.awt.Color(55, 96, 128));
        sugarNo.setForeground(new java.awt.Color(255, 255, 255));
        sugarNo.setText("No");
        sugarNo.setBorder(null);

        aidsYes.setBackground(new java.awt.Color(55, 96, 128));
        aidsYes.setForeground(new java.awt.Color(255, 255, 255));
        aidsYes.setText("Yes");
        aidsYes.setBorder(null);

        aidsNo.setBackground(new java.awt.Color(55, 96, 128));
        aidsNo.setForeground(new java.awt.Color(255, 255, 255));
        aidsNo.setText("No");
        aidsNo.setBorder(null);

        tattooYes.setBackground(new java.awt.Color(55, 96, 128));
        tattooYes.setForeground(new java.awt.Color(255, 255, 255));
        tattooYes.setText("Yes");
        tattooYes.setBorder(null);

        tattooNo.setBackground(new java.awt.Color(55, 96, 128));
        tattooNo.setForeground(new java.awt.Color(255, 255, 255));
        tattooNo.setText("No");
        tattooNo.setBorder(null);

        diabetesYes.setBackground(new java.awt.Color(55, 96, 128));
        diabetesYes.setForeground(new java.awt.Color(255, 255, 255));
        diabetesYes.setText("Yes");
        diabetesYes.setBorder(null);

        diabetesNo.setBackground(new java.awt.Color(55, 96, 128));
        diabetesNo.setForeground(new java.awt.Color(255, 255, 255));
        diabetesNo.setText("No");
        diabetesNo.setBorder(null);

        heartYes.setBackground(new java.awt.Color(55, 96, 128));
        heartYes.setForeground(new java.awt.Color(255, 255, 255));
        heartYes.setText("Yes");
        heartYes.setBorder(null);

        heartNo.setBackground(new java.awt.Color(55, 96, 128));
        heartNo.setForeground(new java.awt.Color(255, 255, 255));
        heartNo.setText("No");
        heartNo.setBorder(null);

        asthamaYes.setBackground(new java.awt.Color(55, 96, 128));
        asthamaYes.setForeground(new java.awt.Color(255, 255, 255));
        asthamaYes.setText("Yes");
        asthamaYes.setBorder(null);

        asthamaNo.setBackground(new java.awt.Color(55, 96, 128));
        asthamaNo.setForeground(new java.awt.Color(255, 255, 255));
        asthamaNo.setText("No");
        asthamaNo.setBorder(null);

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Sugar");

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Aids");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(asthamaYes)
                        .addGap(18, 18, 18)
                        .addComponent(asthamaNo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(heartYes)
                                .addGap(18, 18, 18)
                                .addComponent(heartNo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(diabetesYes)
                                .addGap(18, 18, 18)
                                .addComponent(diabetesNo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sugarYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(sugarNo))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(aidsYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(aidsNo)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tattooYes)
                                    .addGap(18, 18, 18)
                                    .addComponent(tattooNo))))))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sugarYes)
                    .addComponent(sugarNo))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aidsYes)
                    .addComponent(aidsNo))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tattooYes)
                    .addComponent(tattooNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diabetesYes)
                    .addComponent(diabetesNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heartYes)
                    .addComponent(heartNo))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asthamaYes)
                    .addComponent(asthamaNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");

        nameSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        userNameJTextField.setBorder(null);
        userNameJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        userNameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameJTextFieldFocusGained(evt);
            }
        });
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date of Birth");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name");

        nameSeparator.setForeground(new java.awt.Color(255, 255, 255));

        contactNumberJTextField.setBorder(null);
        contactNumberJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        contactNumberJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactNumberJTextFieldFocusGained(evt);
            }
        });
        contactNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Emergency Contact");

        emergencyJTextField.setForeground(new java.awt.Color(255, 255, 255));
        emergencyJTextField.setBorder(null);
        emergencyJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        emergencyJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emergencyJTextFieldFocusGained(evt);
            }
        });
        emergencyJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyJTextFieldActionPerformed(evt);
            }
        });

        nameSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        dobJTextField.setBorder(null);

        genderNameJTextField.setBorder(null);

        pictureLabel.setBackground(new java.awt.Color(255, 255, 255));
        pictureLabel.setForeground(new java.awt.Color(255, 255, 255));
        pictureLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pictureLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(contactNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emergencyJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dobJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel12)
                .addGap(6, 6, 6)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nameSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(contactNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nameSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addComponent(dobJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genderNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(emergencyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nameSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Analyse Requests");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        submitButton.setText("Submit ");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        TextField.setBackground(new java.awt.Color(0, 0, 0));
        TextField.setColumns(20);
        TextField.setForeground(new java.awt.Color(51, 153, 0));
        TextField.setRows(5);
        TextField.setAutoscrolls(false);
        jScrollPane1.setViewportView(TextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(approveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rejectButton)
                            .addComponent(approveButton))
                        .addGap(147, 147, 147))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        submitButton.setEnabled(true);
          if (asthamaYes.isSelected()   && heartYes.isSelected() 
             && aidsYes.isSelected()   && sugarYes.isSelected()
             && tattooYes.isSelected() && diabetesYes.isSelected()) {
              
             Organization org = null;
             
             for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                 if (organization instanceof LabOrganization) {
                    org = organization;
                    break;
                }
            }
             
            if (org != null) {
                request.setCoordinatorStatus("Completed");
                request.setLabStatus("Requested to lab");
                request.setActionDate(new Date());
                org.getWorkQueue().getWorkRequestList().add(request);          
                JOptionPane.showMessageDialog(null, "Request Approved" ,"Info" , JOptionPane.INFORMATION_MESSAGE);
                request.setOverallStatus("Request Approved by Co-ordinator. Now will be assigned to Lab for Tests");
                approveButton.setEnabled(false);
            }else {
                JOptionPane.showMessageDialog(null, "Organization not present" ,"Error" , JOptionPane.ERROR_MESSAGE);
            }

        } else {
             
              JOptionPane.showMessageDialog(null, "All test not passed so need to reject the Request" ,"Info" , JOptionPane.INFORMATION_MESSAGE);
              
        }
        
        
        
    }//GEN-LAST:event_approveButtonActionPerformed

    private void userNameJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldFocusGained

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void contactNumberJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactNumberJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberJTextFieldFocusGained

    private void contactNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberJTextFieldActionPerformed

    private void emergencyJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emergencyJTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyJTextFieldFocusGained

    private void emergencyJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyJTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        submitButton.setEnabled(false);
        approveButton.setEnabled(false);
        rejectButton.setEnabled(false);
        javax.swing.Timer timer3 = new javax.swing.Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = "\nStarting a new Process............................";
                TextField.append(text);
                TextField.setCaretPosition(TextField.getText().length());
                ((javax.swing.Timer)e.getSource()).stop();
            }
        });
        timer3.start();
        javax.swing.Timer timer = new javax.swing.Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = "\nProcessing the Tests ...............";
                TextField.append(text);
                TextField.setCaretPosition(TextField.getText().length());
                ((javax.swing.Timer)e.getSource()).stop();
            }
        });
        timer.start();

        javax.swing.Timer timer1 = new javax.swing.Timer(4000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = "\nValidating the Tests .............";
                TextField.append(text);
                TextField.setCaretPosition(TextField.getText().length());
                ((javax.swing.Timer)e.getSource()).stop();
            }
        });
        timer1.start();
        if (sugarYes.isSelected() && aidsYes.isSelected()
            && tattooYes.isSelected()  && diabetesYes.isSelected()
            && heartYes.isSelected() && asthamaYes.isSelected()) {
            javax.swing.Timer timer2 = new javax.swing.Timer(6000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nYou can approve the request!";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                    ((javax.swing.Timer)e.getSource()).stop();                    
                    approveButton.setEnabled(true);
                }
            });
            timer2.start();
            

        }
        else {
            javax.swing.Timer timer2 = new javax.swing.Timer(6000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String text = "\nReject the Request!";
                    TextField.append(text);
                    TextField.setCaretPosition(TextField.getText().length());
                    ((javax.swing.Timer)e.getSource()).stop();                    
            rejectButton.setEnabled(true);
                }
            });
            timer2.start();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        submitButton.setEnabled(true);
       request.setCoordinatorStatus("Rejected");
       request.setOverallStatus("Requestis Rejected by Co-ordinator");
       request.setActionDate(new Date());
       JOptionPane.showMessageDialog(null, "Request Rejected" ,"Info" , JOptionPane.INFORMATION_MESSAGE);
       rejectButton.setEnabled(false);
    }//GEN-LAST:event_rejectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextField;
    private javax.swing.JRadioButton aidsNo;
    private javax.swing.JRadioButton aidsYes;
    private javax.swing.JButton approveButton;
    private javax.swing.JRadioButton asthamaNo;
    private javax.swing.JRadioButton asthamaYes;
    private javax.swing.JTextField contactNumberJTextField;
    private javax.swing.JRadioButton diabetesNo;
    private javax.swing.JRadioButton diabetesYes;
    private javax.swing.JTextField dobJTextField;
    private javax.swing.JTextField emergencyJTextField;
    private javax.swing.JTextField genderNameJTextField;
    private javax.swing.JRadioButton heartNo;
    private javax.swing.JRadioButton heartYes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator2;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator8;
    private javax.swing.JLabel pictureLabel;
    private javax.swing.JButton rejectButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton sugarNo;
    private javax.swing.JRadioButton sugarYes;
    private javax.swing.JRadioButton tattooNo;
    private javax.swing.JRadioButton tattooYes;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
