/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPages;

//import javafx.scene.paint.Color;
import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Enterprise.Enterprise;
import Backend.Network.Network;
import Backend.Organization.LabOrganization;
import Backend.Organization.Organization;
import Backend.User.User;
import Backend.UserAccount.UserAccount;
import Backend.WorkQueue.CoordinatorTestWorkRequest;
import UI.Admin.AdminDashBoardJPanel;
import UI.Donor.DonorDashBoardJPanel;
import UI.Receiver.ReceiverDashBoardJPanel;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ms
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public LoginPage() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        signUpButton.setVisible(false);
        //signUpBottomTextBox.setVisible(false);
        emailIdTextField.setVisible(false);
        emailIdJlabel.setVisible(false);
        emailIdSeparator.setVisible(false);
        nameJTextField.setVisible(false);
        nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        DonorRadioButton.setVisible(false);
        receiverRadioButton.setVisible(false);
        signInButton.setVisible(true);
        errorForEmailIdLabel.setVisible(false);
        errorForPasswordLabel.setVisible(false);
        //signInBottomTextBox.setVisible(true);
        ButtonGroup group = new ButtonGroup();
        group.add(DonorRadioButton);
        group.add(receiverRadioButton);
        
    }

    LoginPage(boolean sysAdminPressed, boolean employee) {
        initComponents();        
         system = dB4OUtil.retrieveSystem();
        emailIdTextField.setVisible(false);
        emailIdJlabel.setVisible(false);
        emailIdSeparator.setVisible(false);
        nameJTextField.setVisible(false);
        nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        DonorRadioButton.setVisible(false);
        receiverRadioButton.setVisible(false);
        signInButton.setVisible(true);
        errorForEmailIdLabel.setVisible(false);
        errorForPasswordLabel.setVisible(false);
        //signInBottomTextBox.setVisible(true);
        ButtonGroup group = new ButtonGroup();
        group.add(DonorRadioButton);
        group.add(receiverRadioButton);
        if(sysAdminPressed==true){
            signUpButton.setVisible(false);
            signUpLabelTop.setVisible(false);
            signInLabeTop.setVisible(false);
        } //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        userNameJTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        emailIdJlabel = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        DonorRadioButton = new javax.swing.JRadioButton();
        receiverRadioButton = new javax.swing.JRadioButton();
        emailIdSeparator = new javax.swing.JSeparator();
        nameSeparator = new javax.swing.JSeparator();
        nameJTextField = new javax.swing.JTextField();
        errorForEmailIdLabel = new javax.swing.JLabel();
        errorForPasswordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        signInButton = new javax.swing.JLabel();
        signUpButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        signUpLabelTop = new javax.swing.JLabel();
        signInLabeTop = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();

        setLocationByPlatform(true);
        setUndecorated(true);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(860, 600));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(854, 600));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Make a Difference!");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 423, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 430, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 77, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(974, 682));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 250, -1));

        userNameJTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        userNameJTextField.setText("Enter username");
        userNameJTextField.setBorder(null);
        userNameJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        userNameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameJTextFieldFocusGained(evt);
            }
        });
        userNameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 250, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 250, -1));

        passwordField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(null);
        passwordField.setCaretColor(new java.awt.Color(30, 59, 92));
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 250, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 160, 20));

        emailIdJlabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        emailIdJlabel.setForeground(new java.awt.Color(255, 255, 255));
        emailIdJlabel.setText("Email Id");
        jPanel1.add(emailIdJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 160, 20));

        emailIdTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        emailIdTextField.setText("Enter your Email Id");
        emailIdTextField.setBorder(null);
        emailIdTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        emailIdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailIdTextFieldFocusGained(evt);
            }
        });
        emailIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdTextFieldActionPerformed(evt);
            }
        });
        emailIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailIdTextFieldKeyReleased(evt);
            }
        });
        jPanel1.add(emailIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 250, 30));

        DonorRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        DonorRadioButton.setText("Donor");
        jPanel1.add(DonorRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 80, -1));

        receiverRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        receiverRadioButton.setText("Receiver");
        jPanel1.add(receiverRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 90, 20));

        emailIdSeparator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emailIdSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 250, -1));

        nameSeparator.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 250, -1));

        nameJTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        nameJTextField.setText("Enter Name");
        nameJTextField.setBorder(null);
        nameJTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        nameJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameJTextFieldFocusGained(evt);
            }
        });
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 250, 20));

        errorForEmailIdLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errorForEmailIdLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorForEmailIdLabel.setText("!");
        errorForEmailIdLabel.setToolTipText("Please enter a valid Email ID");
        jPanel1.add(errorForEmailIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 20, 30));

        errorForPasswordLabel.setBackground(new java.awt.Color(204, 204, 204));
        errorForPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        errorForPasswordLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorForPasswordLabel.setText("!");
        errorForPasswordLabel.setToolTipText("Password Should be more than 6 character");
        jPanel1.add(errorForPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 20, 30));

        nameLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 160, 20));

        signInButton.setBackground(new java.awt.Color(30, 59, 91));
        signInButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in.png"))); // NOI18N
        signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInButtonMousePressed(evt);
            }
        });
        jPanel1.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 130, 50));

        signUpButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in(1).png"))); // NOI18N
        signUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpButtonMousePressed(evt);
            }
        });
        jPanel1.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 130, 50));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 160, 20));

        signUpLabelTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpLabelTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in(1).png"))); // NOI18N
        signUpLabelTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signUpLabelTopMousePressed(evt);
            }
        });
        jPanel1.add(signUpLabelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 120, 50));

        signInLabeTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInLabeTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in.png"))); // NOI18N
        signInLabeTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInLabeTopMousePressed(evt);
            }
        });
        jPanel1.add(signInLabeTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 130, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginBgv.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -170, 1140, 690));

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 891, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(509, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        userProcessContainer.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int xx,xy; 
    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        LoginPage.super.dispose();
    }//GEN-LAST:event_exitMousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);  
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
         xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void emailIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdTextFieldActionPerformed

    private void signUpLabelTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpLabelTopMousePressed
        // TODO add your handling code here:
        signUpButton.setVisible(true);
        //signUpBottomTextBox.setVisible(true);
        signInButton.setVisible(false);
        //signInBottomTextBox.setVisible(false);
        emailIdTextField.setVisible(true);
        emailIdJlabel.setVisible(true);
        emailIdSeparator.setVisible(true);
        DonorRadioButton.setVisible(true);
        receiverRadioButton.setVisible(true);
         nameJTextField.setVisible(true);
        nameSeparator.setVisible(true);
        nameLabel.setVisible(true);
        errorForEmailIdLabel.setVisible(false);
        errorForPasswordLabel.setVisible(false);
        
    }//GEN-LAST:event_signUpLabelTopMousePressed

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
       passwordField.setText("");
    }//GEN-LAST:event_passwordFieldFocusGained

    private void userNameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTextFieldActionPerformed

    private void userNameJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameJTextFieldFocusGained
        // TODO add your handling code here:
       userNameJTextField.setText("");
    }//GEN-LAST:event_userNameJTextFieldFocusGained

    private void emailIdTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIdTextFieldFocusGained
        // TODO add your handling code here:
     emailIdTextField.setText("");
    }//GEN-LAST:event_emailIdTextFieldFocusGained

    private void signUpButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpButtonMousePressed
        // TODO add your handling code here:
           
           try {
//            if (!checkUserIdExists(userNameJTextField.getText())){
//            JOptionPane.showMessageDialog(null, "UserName Already Present","Warning",JOptionPane.WARNING_MESSAGE);
//            return;
//            }
            
            if (passwordField.getText().length() < 6 ){
            
            JOptionPane.showMessageDialog(null, "Password should be more than 6 characters","Warning",JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            if ( errorForEmailIdLabel.isVisible() == true) {
                
              JOptionPane.showMessageDialog(null, "Email id is wrong","Error",JOptionPane.ERROR_MESSAGE);
              return;   
            
            }
            
            if (DonorRadioButton.isSelected() || receiverRadioButton.isSelected()) {
            
            
            User user = system.getUserDirectory().addUser();
            user.setUserName(userNameJTextField.getText());
            user.setEmailId(emailIdTextField.getText());
            user.setPassword(passwordField.getText());
            user.setName(nameJTextField.getText());

            if (DonorRadioButton.isSelected() == true) {
                user.setType('d');
            } else {
                user.setType('r');
            }

            JOptionPane.showMessageDialog(null, "User Account has been created Successfully");
            emailIdTextField.setText("");
            passwordField.setText("");
            userNameJTextField.setText("");
            nameJTextField.setText("");
            }
            else {
            
            JOptionPane.showMessageDialog(null, "Please select a Donor or Receiver","Error",JOptionPane.ERROR_MESSAGE);
              return; 
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_signUpButtonMousePressed
   
    private boolean checkUserIdExists(String userName) {
        try {
        if (system.getUserDirectory().checkIfUsernameIsUnique(userName)) {
            if (system.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {
                for (Network network : system.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {

                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                return organization.getUserAccountDirectory().checkIfUsernameIsUnique(userName);

                            }

                        } else {
                            return false;

                        }
                    }
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         return false;
    }
    private void nameJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJTextFieldFocusGained
        // TODO add your handling code here:
        nameJTextField.setText("");
    }//GEN-LAST:event_nameJTextFieldFocusGained

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void signInLabeTopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInLabeTopMousePressed
        // TODO add your handling code here:
        signUpButton.setVisible(false);
        //signUpBottomTextBox.setVisible(false);
        emailIdTextField.setVisible(false);
        emailIdJlabel.setVisible(false);
        emailIdSeparator.setVisible(false);
        signInButton.setVisible(true);
        //signInBottomTextBox.setVisible(true);
        DonorRadioButton.setVisible(false);
        receiverRadioButton.setVisible(false);
        nameJTextField.setVisible(false);
        nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        errorForEmailIdLabel.setVisible(false);
        errorForPasswordLabel.setVisible(false);
    }//GEN-LAST:event_signInLabeTopMousePressed

    private void signInButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMousePressed
        // TODO add your handling code here:
        // Get user name
        try {
        User user;
        user = system.getUserDirectory().authenticateUser(userNameJTextField.getText(), passwordField.getText());

        if(user!=null){

            if (user.getType() == 'd') {

                DonorDashBoardJPanel donorPanel = new DonorDashBoardJPanel(dB4OUtil,system,user);
                userProcessContainer.add("DonorDashBoardJPanel",donorPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                donorPanel.setVisible(true);

            } else {
                ReceiverDashBoardJPanel receiverPanel = new ReceiverDashBoardJPanel(dB4OUtil,system,user);
                userProcessContainer.add("ReceiverDashBoardJPanel",receiverPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                receiverPanel.setVisible(true);
            }
        }
        else{

            String userName = userNameJTextField.getText();
            // Get Password
            char[] passwordCharArray = passwordField.getPassword();
            String password = String.valueOf(passwordCharArray);

            //Step1: Check in the system admin user account directory if you have the user
            UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);

            Enterprise inEnterprise=null;
            Organization inOrganization=null;

            if(userAccount==null){
                //Step 2: Go inside each network and check each enterprise
                for(Network network:system.getNetworkList()){
                    //Step 2.a: check against each enterprise
                    for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                        userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if(userAccount==null){
                            //Step 3:check against each organization for each enterprise
                            for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                                userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if(userAccount!=null){
                                    inEnterprise=enterprise;
                                    inOrganization=organization;
                                    break;
                                }
                            }

                        }
                        else{
                            inEnterprise=enterprise;
                            break;
                        }
                        if(inOrganization!=null){
                            break;
                        }
                    }
                    if(inEnterprise!=null){
                        break;
                    }
                }
            }

            if(userAccount==null){
                JOptionPane.showMessageDialog(null, "Invalid credentials");
                return;
            }
            else{

                userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, system,dB4OUtil);

            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_signInButtonMousePressed

    private void emailIdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailIdTextFieldKeyReleased
        // TODO add your handling code here:
        
        String patternForEmail = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";
        String emailID = emailIdTextField.getText();
        Pattern patternForEmailId = Pattern.compile(patternForEmail);
        Matcher matcherForEmailId = patternForEmailId.matcher(emailID);
        if (matcherForEmailId.matches() == false) {
            errorForEmailIdLabel.setVisible(true);
        } else {
            errorForEmailIdLabel.setVisible(false);
        }
    }//GEN-LAST:event_emailIdTextFieldKeyReleased

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        // TODO add your handling code here:
        if (passwordField.getText().length() < 6) {
            errorForPasswordLabel.setVisible(true);
        } else {
            errorForPasswordLabel.setVisible(false);
        }
        
    }//GEN-LAST:event_passwordFieldKeyReleased
        

public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(171,204,61));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DonorRadioButton;
    private javax.swing.JLabel emailIdJlabel;
    private javax.swing.JSeparator emailIdSeparator;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JLabel errorForEmailIdLabel;
    private javax.swing.JLabel errorForPasswordLabel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JRadioButton receiverRadioButton;
    private javax.swing.JLabel signInButton;
    private javax.swing.JLabel signInLabeTop;
    private javax.swing.JLabel signUpButton;
    private javax.swing.JLabel signUpLabelTop;
    private javax.swing.JTextField userNameJTextField;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    

    
}
